# 1. 创建数组

In [3]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b)
b[1, 1] = 10
print(b)
print(a.shape)
print(b.shape)
print(a.dtype) # 查看a矩阵中数据的类型

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]
(3,)
(3, 3)
int32


# 2. 结构数组


In [5]:
import numpy as np
persontype = np.dtype({
    'names' : ['name', 'age', 'chinese', 'math', 'english'],
    'formats' : ['S32', 'i', 'i', 'i', 'f']})
peoples = np.array([("ZhangFei", 32, 75, 100, 90), ("GuanYu", 24, 85, 96, 88.5), ("ZhaoYun", 28, 85, 92, 96.5), ("HuangZhong", 29, 65, 85, 100)], dtype = persontype)
ages = peoples[:]['age']
chineses = peoples[:]['chinese']
maths = peoples[:]['math']
englishs = peoples[:]['english']
print(np.mean(ages)) # mean是求平均值
print(np.mean(chineses))
print(np.mean(maths))
print(np.mean(englishs))

28.25
77.5
93.25
93.75


# 3. 连续数组的创建

In [9]:
x1 = np.arange(1, 11, 2)
x2 = np.linspace(1, 9, 5)
print(x1)
print(x2)
print(x1.dtype)
print(x2.dtype)

[1 3 5 7 9]
[1. 3. 5. 7. 9.]
int32
float64


# 4. 算数运算

In [10]:
x1 = np.arange(1, 11, 2)
x2 = np.linspace(1, 9, 5)
print(np.add(x1, x2))
print(np.subtract(x1, x2))
print(np.multiply(x1, x2))
print(np.divide(x1, x2))
print(np.power(x1, x2))
print(np.remainder(x1, x2))

[ 2.  6. 10. 14. 18.]
[0. 0. 0. 0. 0.]
[ 1.  9. 25. 49. 81.]
[1. 1. 1. 1. 1.]
[1.00000000e+00 2.70000000e+01 3.12500000e+03 8.23543000e+05
 3.87420489e+08]
[0. 0. 0. 0. 0.]


# 5. 统计函数

In [11]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.amin(a))
print(np.amin(a, 0)) # 0代表找每一列最小值
print(np.amin(a, 1)) # 1代表找每一行最小值
print(np.amax(a))
print(np.amax(a, 0)) # 找每一列最大值
print(np.amax(a, 1)) # 找每一行最大值

1
[1 2 3]
[1 4 7]
9
[7 8 9]
[3 6 9]


In [12]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.ptp(a))
print(np.ptp(a, 0)) # 找每一列最大值跟最小值之差
print(np.ptp(a, 1)) # 找每一行最大值跟最小值之差

8
[6 6 6]
[2 2 2]


In [13]:
# 统计数组的百分位数
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.percentile(a, 50)) # 第二个参数代表p，p的取值范围是0-100，如果p=0.那么是求最小值，p=50就是求平均值，p=100就是求最大值
print(np.percentile(a, 50, axis = 0))
print(np.percentile(a, 50, axis = 1))

5.0
[4. 5. 6.]
[2. 5. 8.]


In [15]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# 求中位数
print(np.median(a))
print(np.median(a, axis = 0))
print(np.median(a, axis = 1))
# 求平均数
print(np.mean(a))
print(np.mean(a, axis = 0))
print(np.mean(a, axis = 1))

5.0
[4. 5. 6.]
[2. 5. 8.]
5.0
[4. 5. 6.]
[2. 5. 8.]


In [16]:
# 统计数组中的加权平均值
a = np.array([1, 2, 3, 4])
wts = np.array([1, 2, 3, 4])
print(np.average(a)) # （1 + 2 + 3 + 4)/4 = 2.5
print(np.average(a, weights = wts)) # (1 * 1 + 2 * 2 + 3 * 3 + 4 * 4)/(1 + 2 + 3 + 4) = 3.0

2.5
3.0


In [17]:
a = np.array([1, 2, 3, 4])
print(np.std(a)) # 求这组数据的标准差
print(np.var(a)) # 求这组数据的方差

1.118033988749895
1.25


In [19]:
# 排序
a = np.array([[4,3,2],[2,4,1]])
print(np.sort(a)) # 即按axis = -1也就是=1来排
print(np.sort(a, axis=None)) # 当作一个向量来排
print(np.sort(a, axis=0))  
print(np.sort(a, axis=1))  

[[2 3 4]
 [1 2 4]]
[1 2 2 3 4 4]
[[2 3 1]
 [4 4 2]]
[[2 3 4]
 [1 2 4]]


# 6. 练习题
统计全班的成绩
姓名 语文 数学 英语

In [45]:
import numpy as np
def printScore(name, container):
    print('%s | %f | %d | %d | %f | %f' %(name, np.mean(container), np.amin(container), np.amax(container), np.var(container), np.std(container)))
    
studenttype = np.dtype({'names' : ['name', 'chinese', 'english', 'math', 'total'], 'formats' : ['U32', 'i', 'i', 'i', 'i']}) # 中文类型不能用S32，S只支持ascii编码
students = np.array([('张飞', 66, 65, 30, 0), ('关羽', 95, 85, 98, 0), ('赵云', 93, 92, 96, 0), ('黄忠', 90, 88, 77, 0), ('典韦', 80, 90, 90, 0)], dtype = studenttype)
students['total'] = students['chinese'] + students['math'] + students['english']
chinese = students['chinese']
english = students['english']
math = students['math']

print('----------成绩统计----------')
print('科目 | 平均成绩 | 最小成绩 | 最大成绩 | 方差 | 标准差')
printScore('语文', chinese)
printScore('英语', english)
printScore('数学', math)
print('未按总成绩排序前：%s' %students)
print('按总成绩排序后：%s' %np.sort(students, order = 'total')[::-1]) # 按总分先从小到大排序后再反转数组


----------成绩统计----------
科目 | 平均成绩 | 最小成绩 | 最大成绩 | 方差 | 标准差
语文 | 84.800000 | 66 | 95 | 114.960000 | 10.721940
英语 | 84.000000 | 65 | 92 | 95.600000 | 9.777525
数学 | 78.200000 | 30 | 98 | 634.560000 | 25.190474
未按总成绩排序前：[('张飞', 66, 65, 30, 161) ('关羽', 95, 85, 98, 278) ('赵云', 93, 92, 96, 281)
 ('黄忠', 90, 88, 77, 255) ('典韦', 80, 90, 90, 260)]
按总成绩排序后：[('赵云', 93, 92, 96, 281) ('关羽', 95, 85, 98, 278) ('典韦', 80, 90, 90, 260)
 ('黄忠', 90, 88, 77, 255) ('张飞', 66, 65, 30, 161)]
