# 1. 4\*4随机数组测试

In [2]:
from numpy import *
random.rand(4,4)

array([[0.45049531, 0.97964751, 0.93192805, 0.6276839 ],
       [0.10106935, 0.67307688, 0.37955861, 0.76056186],
       [0.71927667, 0.74203284, 0.54339619, 0.98327751],
       [0.00954826, 0.16407505, 0.18795485, 0.10861836]])

# 2. 调用mat()函数将数组转化为矩阵

In [9]:
randMat = mat(random.rand(4,4))
randMat

matrix([[0.54440189, 0.79972448, 0.54552244, 0.84399957],
        [0.14241114, 0.83511752, 0.83795975, 0.16906282],
        [0.22766547, 0.04554466, 0.46618854, 0.78364551],
        [0.55936265, 0.43912616, 0.62100739, 0.67173396]])

# 3. 使用.I操作符实现矩阵求逆的运算

In [10]:
invRandMat = randMat.I
invRandMat

matrix([[-0.79610824, -1.05498085, -2.06080201,  3.66992204],
        [ 1.75741924,  0.35745863, -0.653839  , -1.53530432],
        [-1.86620464,  1.08954872,  0.69994836,  1.25401186],
        [ 1.23934677, -0.36245056,  1.49639653, -1.72296729]])

# 4. 矩阵乘法

In [13]:
randMat * invRandMat

matrix([[ 1.00000000e+00, -1.35308431e-16, -1.11022302e-16,
          4.44089210e-16],
        [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
          2.22044605e-16],
        [-2.22044605e-16,  5.55111512e-17,  1.00000000e+00,
          4.44089210e-16],
        [ 2.22044605e-16,  2.77555756e-17,  0.00000000e+00,
          1.00000000e+00]])

# 5. 使用eye(4)创建4x4的单位矩阵

In [15]:
myEye= randMat * invRandMat
myEye - eye(4)

matrix([[ 2.22044605e-16, -1.35308431e-16, -1.11022302e-16,
          4.44089210e-16],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          2.22044605e-16],
        [-2.22044605e-16,  5.55111512e-17, -2.22044605e-16,
          4.44089210e-16],
        [ 2.22044605e-16,  2.77555756e-17,  0.00000000e+00,
          2.22044605e-16]])

In [16]:
eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])