In [1]:
import numpy as np
arr1 = np.array([2, 3, 4])
print(arr1)
print(arr1.dtype)

arr2 = np.array([2.1, 3.1, 4.1])
print(arr2)
print(arr2.dtype)
print(arr1 + arr2)

[2 3 4]
int32
[2.1 3.1 4.1]
float64
[4.1 6.1 8.1]


In [5]:
# Numpy数组和标量的计算
print(arr2 * 10)
data = [[1,2,3], [4,5,6]]
arr3 = np.array(data) # 将列表转为二维矩阵
print(arr3)
print(arr3.dtype)
print(type(arr3))

[21. 31. 41.]
[[1 2 3]
 [4 5 6]]
int32
<class 'numpy.ndarray'>


In [10]:
print(np.zeros(10)) # 定义了一个一维的长度为10的数组，这个数组的所有值都是0
print(np.zeros((3, 5))) # 定义一个3x5的矩阵，这个矩阵的所有值为0
print(np.ones((4, 6))) # 定义一个4x6的矩阵，初始值都为1
print(np.empty((2,3,2))) # 定义了一个三维矩阵，初始值为随机值

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [19]:
# Numpy数组的索引和切片
arr4 = np.arange(10)
print(arr4[5])
print(arr4[5:8])
arr4[5:8] = 0
print(arr4)
arr_slice = arr4[5:8]
arr_slice[:] = 1 # 由于python这里是引用，故而这么做会影响到arr4的内容
print(arr4)
arr_slice = arr4[5:8].copy()
arr_slice[:] = 0 # 这样子做操作不会影响arr4，因为它是arr4的一个副本
print(arr4)
print(arr_slice)
arr5 = np.array(['a', 'b', 'c', 'd'])
print(arr5[1]) # 下标从0开始计算

5
[5 6 7]
[0 1 2 3 4 0 0 0 8 9]
[0 1 2 3 4 1 1 1 8 9]
[0 1 2 3 4 1 1 1 8 9]
[0 0 0]
b
